---
- name: Install and configure PostgreSQL
  hosts: 127.0.0.1
  become: yes
  tasks:
    - name: Install required dependencies (psycopg2)
      apt:
        name: python3-psycopg2
        state: present
        update_cache: yes

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present
        update_cache: yes

    - name: Ensure PostgreSQL service is running
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Create a new PostgreSQL database
      become: yes
      become_user: postgres
      postgresql_db:
        name: "postgress_db"
        owner: postgres
        encoding: UTF8
        state: present

    - name: Create PostgreSQL user
      become: yes
      become_user: postgres
      postgresql_user:
        db: "postgress_db"
        name: "postgres"
        password: "password"
        priv: ALL

    - name: Execute SQL commands to populate database
      become: yes
      become_user: postgres
      postgresql_query:
        db: postgres_db
        query: "DROP TABLE IF EXISTS posts; CREATE TABLE IF NOT EXISTS posts (id SERIAL PRIMARY KEY, title TEXT NOT NULL, body TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP); INSERT INTO posts (title, body) VALUES ('First Post', 'This is my first post'), ('Second Post', 'This is my second post'), ('Third Post', 'Here is my third post!!!');"
...